# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  linkmessageapi:
    image: linkmessageapi
    build:
      context: .
      dockerfile: Examples/Link/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - code-test-net

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
    volumes:
      - smtp4dev-data:/smtp4dev
    networks:
      - code-test-net

volumes:
  smtp4dev-data:

networks:
  code-test-net:
    driver: bridge